### ISSUE TITLE
Error running equilibration

### ISSUE THREAD

**Issue by vemaparna** [Gallicchio-Lab/AToM-OpenMM#12]
Hi!
Very delighted to use your plugin. It is simply awesome. I could run the tutorials without any error. But when i tried to build my own systems for RBFE , the simulation crashes with an error " Particle coordinate is nan"
To avoid this I have minimised the protein-ligand complex in opemm seperately and used the equilibrated protein file as input. Now the script  "setup-atm.sh" is picking up all the atoms of protein as atoms of one of the ligand and then crashes during the equilibrium phase. The protein files looks decent with no errors. Couldnt identify from where the probelm arise. please find the link of protein, ligands and the script used ( since my protein has ZN, i had to modify the script file to include ZN parameter in leap)
https://drive.google.com/drive/folders/1fNb5ySlZDX9vk_uFMEAXO6-SDQ2UEFeq?usp=share_link

Can you help me to rectify this?

**Comment by egallicc** [comment]
Thank you for the feedback @vemaparna.

It is a good idea to investigate whether it is a crash due to the alchemical settings or the molecular system itself. Assuming you are using the packaged [structure preparation tool](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/master/rbfe_structprep.py), edit the control file (`<jobname>_asyncre.cntl`)  and reset the alchemical restraints:
```
CM_KF = 0.00
POSRE_FORCE_CONSTANT = 0.0
ALIGN_KF_SEP = 0.0
ALIGN_K_THETA = 0.0
ALIGN_K_PSI = 0.0
```
With these changes, minimization and equilibration with NPT and NVT will proceed as for any other standard OpenMM system. If the system goes through these steps without errors, then it is likely that the alchemical-related settings (Vsite, alignment restraints, etc.) are not set properly.

**Comment by vemaparna** [comment]
Thanks a lot. I could figureout the problem. My mol2 files were generated by pymol that added an extra line inside the file, misguiding the scripts to fetch all the protein atoms as ligand atoms. I regenerated mol2 files using Openbabel. It works.

**Comment by egallicc** [comment]
Thank you for the feedback. AToM unfortunately does not make system setup for MD any easier. It probably adds fewer complications than other alchemical methodologies do. But, yes, weird setup issues remain.
