### ISSUE TITLE
Extending the FKBP example to a new protein system?

### ISSUE THREAD

**Issue by JSLJ23** [Gallicchio-Lab/AToM-OpenMM#15]
Hi, I am interested to extend these ABFE calculations to model a protein and small molecule ligand system with known ground truth data and I was wondering what are the major necessary changes following the FKBP example that I need to make in order to fit this new system.

1. The individual protein.pdb file and ligand.mol2 files.
2. The list of ligand names in `setup-settings.sh`.
3. The residue IDs that define the binding site.

Is there anything else that needs to be other than this?

**Comment by JSLJ23** [comment]
Also, I was wondering how is the displacement vector derived from just the information of the displacement distances? Does it involve some calculation with the coordinates of the ligand centroid, protein binding site coordinates and displacement distance vector? I wanted to know this to specify the necessary information for the displacement vector to be representative for the new system I had in mind.

**Comment by egallicc** [comment]
I think you have listed the main elements. Also consider, depending on the specific system:

- The radius of the Vsite spherical binding site region (the CM_TOL value)
- The atoms of each ligand that define the CM of the ligand. The distance between the CM of the ligand and the CM of the binding site residues is what determines the bound region. For small ligands, as in this example, all of the atoms of the ligand are considered. But for larger ligands, it might make sense to restrict the definition to some core group. Again, depending on the specific system under consideration.
- The displacement vector is totally arbitrary as long as it displaces the ligand far away from the receptor. In practice, be reasonable about the magnitude of the displacement because the solvent box size increases proportionally to it. The displacement vector is unrelated to the binding site definition (Vsite). The displacement is used to compute the perturbation energy (the change in potential energy before and after the displacement). Vsite defines the binding site region, a necessary parameter for the definition of the ABFE.
- Some of these parameters are set in `setup-settings.sh`. Others require editing `asyncre_template.cntl` and/or modifications of the `setup-atm.sh` script.
- We have not yet documented it, but AToM-OpenMM has now an `abfe_structprep.py` tool similar to the `rbfe_structprep.py` tool to do minimization, equilibration, etc. I recommend using it. See the [CDK2 tutorial](https://github.com/Gallicchio-Lab/AToM-OpenMM/tree/master/examples/RBFE/cdk2).
- Keep in mind that ABFE alchemical methods are severely limited in terms of ligand size. It is tough to converge ABFEs for ligands larger than ~10-15 heavy atoms, especially if binding induces conformational reorganization of the ligand and receptor. Occluded hydration sites can also be major obstacles.
