### ISSUE TITLE
Questions re: replica `.out` files for `temoa-g1` ABFE example.

### ISSUE THREAD

**Issue by dominicrufa** [Gallicchio-Lab/AToM-OpenMM#3]
@egallicc , I am looking to do my own analysis with [MBAR](https://aip.scitation.org/doi/10.1063/1.2978177) on the output of the `temoa-g1` ABFE replica example (specifically the replica `.out` files), and I am trying make sure my units and parameter references are correct.

First, from [this line](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/53167b4e936f1922ce72abb452bedb52124bc582/ommreplica.py#L162), I presume that all of the replica `.out` energies are in kcal/mol.

Second, from [this line](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/53167b4e936f1922ce72abb452bedb52124bc582/ommreplica.py#L186), am I correct in saying that the perturbation energy [here](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/da04d8d6a8aaf46c6bb0d88883d8053512788bdf/ommworker.py#L361) (second to last col of replica `.out` files) is equal to the W_{\lambda} term in eq.1 of the [ATM-ABFE paper](https://pubs.acs.org/doi/10.1021/acs.jctc.1c00266), and that the potential energy (third to last column) is equal to the LHS of the same equation? 

Apologies for all of the questions.

**Comment by egallicc** [comment]
Yes, the `pert_energy/kilocalories_per_mole` statement ensures that the printed value of the perturbation energy is in kcal/mol.

No, the perturbation energy corresponds to `u(x)` defined by eq. 2 of Wu et al. (2021).  Your MBAR script would need to turn this into the alchemical potential energy in eq.1.

Yes, the third to last column is indeed the LHS of eq.1. However, it is not very useful for alchemical thermodynamic reweighting because it gives the potential energy of the system at the lambda value at which it was collected. During the thermodynamic reweighting procedure one would need the corresponding quantity of that sample at all lambda values. Samples of the perturbation energy `u` allows you to do just that algebraically by using eqs. 1 and 3 in that paper.

**Comment by dominicrufa** [comment]
> Yes, the third to last column is indeed the LHS of eq.1. However, it is not very useful for alchemical thermodynamic reweighting because it gives the potential energy of the system at the lambda value at which it was collected. During the thermodynamic reweighting procedure one would need the corresponding quantity of that sample at all lambda values. Samples of the perturbation energy u allows you to do just that algebraically by using eqs. 1 and 3 in that paper.

yes, you read my mind. and thank you for the clarification.
