### ISSUE TITLE
MD has crashed and No compute devices are alive. Quitting

### ISSUE THREAD

**Issue by cn-lugen** [Gallicchio-Lab/AToM-OpenMM#34]
Hello, I always encounter this problem frequently when using, how can I solve it?  The problem is in my MD system, or the parameter setting error of "asyncre.cntl", I hope someone can give me any tips, thank you very much.
![1687328476165](https://github.com/Gallicchio-Lab/AToM-OpenMM/assets/70088757/5e6db5c2-0677-43e5-8928-3ec9073650bc)

My GPU is in normal idle state

![1687328790554](https://github.com/Gallicchio-Lab/AToM-OpenMM/assets/70088757/28a57749-f484-433d-81f9-656075856a29)

**Comment by egallicc** [comment]
In our experience, frequent MD crashes are likely caused by setup issues. Depending on your application (ABFE or RBFE) possible things to check are:

1. list of ligand atoms
2. reference alignment atoms: if they are actually aligned in the starting structure and if they could become colinear when the ligands change conformation.
3. the displacement vector should take the ligand(s) in a region of the solvent where they do not overlap with receptor atoms
4. the definition of the binding site

In ABFE we also see frequent crashes with large ligands and with RBFE if the two ligands are very different. These are due to the inherent limitations of the FEP approach. There is no known workaround except breaking up the transformations into a set of manageable steps.

**Comment by cn-lugen** [comment]
@egallicc  

Thank you very much for your prompt. I carefully checked the parameter Settings in the early stage of calculation. The problem did come from my Settings, and the "displacement" I set was unreasonable. At present, the program is running normally.
Thank you very much again for your help, this question can be closed, I hope it can help other people who encounter this problem.
