### ISSUE TITLE
ERROR - async_re.openmm_async_re - MD has crashed

### ISSUE THREAD

**Issue by cn-lugen** [Gallicchio-Lab/AToM-OpenMM#36]
I had previously opened a problem that could be re-executed when I re-modified "setup-settings.sh", but when I re-tried to calculate the absolute binding free energy of another protein and substrate, the error occurred again.   I hope you can take a look at my parameter file to determine where my question is coming from, thank you very much.
[w-7-21.zip](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/12135786/w-7-21.zip)

**Comment by egallicc** [comment]
The ligand is far too large for ABFE estimation. As you can see in 'Rplots.pdf', the perturbation energy distributions do not overlap. The crash likely occurs because the alchemical intermediate is too strained. An optimized non-linear alchemical potential could help slightly but I doubt that any direct alchemical approach would work for this system. Try the break up the transformation into manageable steps. First bind a small fragment, then progressively grow it with a series of RBFE steps. Here is an [example](https://arxiv.org/abs/2302.08620) of this approach.

**Comment by cn-lugen** [comment]
Thank you very much for your advice, after trying, when I reduced the substrate to 19 heavy atoms, ABFE could run smoothly and ran for 24 hours without reporting any errors, after which I will try to use the RBFE method to further increase the size of the substrate until the size of the substrate is as large as I want to calculate. Thanks to the tools you developed, this automated binding energy calculation tool is very convenient.

I have a little suggestion, it seems that only WALL_TIME can control the calculation time in cntl file, I hope there can be other keywords such as the number of cycles and so on to control the calculation time. (For example, if I want to compare the absolute binding free energy of a molecule with different receptors, let's say I let them run for the same amount of time, but then restart after a task is killed in the middle, or if the two receptors have a certain size difference, which may make their samples inconsistent)
Thank you anyway
