### ISSUE TITLE
On the influence on changes of the .cntl file in other systems

### ISSUE THREAD

**Issue by qsabanes** [Gallicchio-Lab/AToM-OpenMM#38]
Hi!
Opening this here since I think it will get more traction and will be easier to notice. I've seen that in a recent [pre-print](https://arxiv.org/pdf/2308.08671.pdf) were ATM is performed on the Merck dataset a series of flags in the setup/.cntl file are changed in comparison to the tutorial files in this repo. [https://github.com/EricChen521/ATM_MerckSet/tree/main](https://github.com/EricChen521/ATM_MerckSet/tree/main).
Flags such as `ALIGN_K_THETA` and `ALIGN_K_PSI` are changed as well as the `W0COEFF`. How much would that imply on the stability, performance of the system? Asking because I tried these same systems with a .cntl file very similar to the CDK2 tutorial one and I was getting many Energy NaN for several ligand pairs, even with the index restraints provided in this repo. Once I changed the values in the .cntl file, all run smoothly.

Furthermore, is there a reasoning behind the number of `PRODUCTION_STEPS`? Could that be changed taking into account that others should be adapted or it would also affect performance?

Thanks!

**Comment by egallicc** [comment]
Hi. In my opinion, most of those differences are not significant in terms of avoiding instabilities. The force constants of the alignment restraints are indeed larger for Merck's benchmark calculations than the CDK2 example, but only by a factor of 2. The alchemical schedule seems to me identical. Can you please point out the specific differences?

One significant difference is maybe the lack of binding site restraints in Merck's benchmark calculations (`CM_KF = 0`). We decided to forego binding site restraints because we were not able to easily automate the choice of the receptor's binding site residues in that study. Binding site restraints are not critical when comparing a pair of strong binders that are not expected to float away from the receptor. Crashes are expected when binding site restraints are on but they are set incorrectly.

`PRODUCTION_STEPS` regulates how many MD steps a replica performs on the GPU before being checkpointed to CPU memory. The shorter `PRODUCTION_STEPS`, the more often a replica is checkpointed and participates in replica exchanges. However, this comes at the cost of transferring coordinates and velocities between the CPU and GPU more often. As a general guideline, `PRODUCTION_STEPS` should be large enough so that each replica spends at least a couple of minutes on the GPU to offset the time it takes to transfer data to and from the GPU.

**Comment by egallicc** [comment]
@EricChen521

**Comment by qsabanes** [comment]
You are right, there's nothing different on the alchemical schedule. My bad on there.
One thing I thought it could be possible was running the sims at a larger timestep (4fs) could cause some of the crashes/NaNs? At many points 1/2 of the ligand pairs in a target were crashing at some point. Now I'll try with the settings from the latest manuscript.

Regarding `PRODUCTION_STEPS`, if I understood correctly it should be just a matter of performance right? More or less `PRODUCTION_STEPS` should not influence in the results obtained considering we sample for the same amount of aggregate time.

**Comment by egallicc** [comment]
A 4 fs time-step requires a "heavy" hydrogen (like `HMASS = 1.5`). Do you have that?

Yes, `PRODUCTION_STEPS`, in principle, affects performance, not accuracy. In practice, however, the level of conformational sampling in a finite-length simulation could matter. A shorter `PRODUCTION_STEPS` allows a replica to exchange more often and improve conformational sampling at the expense of computational speed. Probably a good criterion is to find the smallest value of `PRODUCTION_STEPS` that leads to a ~90% GPU utilization. That way, you are maximizing exchanges without substantially affecting throughput.

**Comment by egallicc** [comment]
We did not have significant issues on the 500+ RBFE calculations. Test without the binding site restraints `CM_KF=0` to see if the crashes are due to incorrect settings. 

As we describe in the paper, some transformations in the Merck set are very extensive and did not converge. These are also likely to lead to sporadic crashes due to strained alchemical intermediates. However, these too reached completion with the help of the ASyncRE restart mechanism.

We used a custom force field.

Early on we experienced crashes due to bad initial structures. We addressed those by restraining more carefully the ligand during equilibration. The improved equilibration protocol is implemented in the `structprep` utility. So, if you are using it, bad structures are unlikely the origin of the crashes you are seeing.

**Comment by qsabanes** [comment]
Can say that with these new parameters everything worked much smoothly. Stability and accuracy wise

**Comment by egallicc** [comment]
Great. I think this suggests that the CMs of the ligand and receptor site were not always within tolerance. Automating the selection of the binding site region is tricky ...

**Comment by smutao** [comment]
> Great. I think this suggests that the CMs of the ligand and receptor site were not always within tolerance. Automating the selection of the binding site region is tricky ...

Dear Professor Gallicchio,

Concerning this binding site-ligand restraint, another possibility I was thinking about is to change the CM-CM restraint into positional restraint on certain ligand atoms. 

In this direction, I modified some code in the v4.0.0rc branch and try to use ligand positional restraint (along with the existing positional restraint for protein) if user puts 'CM_KF' as a negative value. The LIGAND_CM_ATOMS [for abfe] (and LIGAND1/2_CM_ATOMS [for rbfe]) will be reused. The 'CM_TOL' value will also be reused. Please see the attached '.diff' file. 

Would this be a viable alternative? Hope to hear your opinion. Thanks a lot!  

[diff-file](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/12644071/try_to_add_ligand_posres.diff.txt)
