### ISSUE TITLE
About LIGAND1/2_CM_ATOMS 

### ISSUE THREAD

**Issue by smutao** [Gallicchio-Lab/AToM-OpenMM#39]
Dear Professor Gallicchio,

I saw in two 'asyncre_template.cntl' files for RBFE that the LIGAND1_CM_ATOMS or LIGAND2_CM_ATOMS is set to  either all atoms of a ligand or the 1st atom of reference atoms (in total 3). 

My question is: should we always choose the 1st reference atoms as the center-of-mass atom or it depends? If you have some suggestions, please feel free to share. 

Thanks a lot!

**Comment by egallicc** [comment]
The CM of large ligands could be displaced from the "center" of the ligand. It could also move around in wanted ways while the internal conformation of the ligand changes. In these cases, setting the CM as the position of the first reference atom is a good alternative, since often the first reference atom is picked to represent the origin, or "center," of the ligand.

**Comment by smutao** [comment]
Thanks a lot for your helpful insights!
