### ISSUE TITLE
Vector setting and binding site questions

### ISSUE THREAD

**Issue by quantaosun** [Gallicchio-Lab/AToM-OpenMM#4]
Hi, 

I got several questions. Help is appreciated.

I am confused about how to determine the vector values for my system. What I did was use the coordinate of faraway water to subtract my ligand's coordinate. Could anyone help me understand this value, is it supposed to be all positive values? Since, in my case, I provide a vector value, for example,  [ 10, 11, -6], looks quite different from what is in the tutorial.

Second, can I see if the ligand was removed from the binding site and appeared at the solvent at some stage of the simulation, I mean visually?

Third, is the calculation sensitive to the binding site residue ID numbers ? Since to define a binding pocket for a protein time, there are more than 20 residues, should I include them all, or maybe just a few critical residues?

The last question is, I have noticed my Rplot has a huge gap as attached. I assume this is not good, right? 

[Rplots.pdf](https://github.com/Gallicchio-Lab/AToM-OpenMM/files/9466718/Rplots.pdf)

Apologies if there are too many questions.

**Comment by egallicc** [comment]
I answer assuming that you are asking about an absolute binding free energy (ABFE) setup rather than a relative one.

The displacement vector is the quantity added to the position of each atom of the ligand in the binding site to place it into the solvent bulk. It is, in principle, arbitrary as long the resulting position in the bulk is far away from any atoms of the receptor. The rule of thumb is 3 or more hydration layers. Choosing a very long displacement is not wrong but results in a very large solvent box and poor MD performance. The tutorial is only an example. It is not meant to be representative for any other system.

The ligand should always appear as bound to the receptor in ABFE trajectories. That is, it should remain within the binding site region. This is necessarily the case if Vsite binding site restraints are in place. Something is seriously wrong with the simulation if the ligand is found outside the binding site region. Note that, depending on the alchemical state, the ligand might be decoupled from the receptor and coupled to the solvent. To see the ligand in its position in the solvent bulk, apply a translation equal to the displacement vector. This is easily accomplished in VMD using the `moveby` command. 

The binding site region of protein receptors is usually defined in terms of the center of mass CM of the Calpha atoms of a set of residues. It could be any number of residues, as long as their CM is near the center of the chosen binding site region.

Yes, a large binding energy gap in the alchemical probability distributions indicates a major problem. We see it when simulations fail because of bad setup but also for valid setups of alchemical transformations that are just too extensive. For example, when trying to obtain the ABFE of a large ligand. We devised a bunch of "tricks" discussed in our recent publications to extend the ATM ABFE protocol to larger ligands. But I have not seen anything that works with more than 15-20 heavy atoms. The RBFE protocol does not have a specific ligand size limitation. It is limited by the magnitude of the transformation.

**Comment by quantaosun** [comment]
Hi,

Yes, all my previous questions are about ABFE.

Thanks very much for your explanation.

In my case, all my ligands have more than 22 heavy atoms, so seems better to use the RBFE workflow.

AToM method is easy to use especially considering it builds directly on OpenMM. Looking forward to seeing it become better and better.

**Comment by egallicc** [comment]
Great. Sure, thanks, we are here to help.
