### ISSUE TITLE
cd: too many arguments

### ISSUE THREAD

**Issue by sobertie** [Gallicchio-Lab/AToM-OpenMM#54]
I am trying to find out the absolute free binding energy of HDAC11 molecule with some ligands of my choice. But when I execute setup-atm.sh; it is showing following error -  ./scripts/setup-atm.sh: line 25: cd: too many arguments. Can anyone help me with that ?

**Comment by egallicc** [comment]
Assuming [this line](https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/d157e227afff48d89243ab02df1bb45efc3dc696/examples/ABFE/fkbp/scripts/setup-atm.sh#L25C2-L25C40) causes it, I am guessing that it could be due to the receptor and/or the ligand having a whitespace character in their names. Try:
```
cd "${work_dir}/complexes/${jobname}"
```
But a space in the name is likely to cause many other problems. If it is a space, I recommend renaming the ligand.

**Comment by egallicc** [comment]
Closing this, assuming it is resolved. Reopen if needed.
