### ISSUE TITLE
Is ligand alignment in the initial state necessary in RBFE? 

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#63]
What will happen if the initial posture is different?

**Comment by 9527567** [comment]
Sorry to bother you again, there are still a few questions.
Question 1: If the binding modes of two ligands are different, would aligning them have a significant impact on the results?
Question 2: Is alignment flexible or rigid?

**Comment by egallicc** [comment]
1. In principle, no. As long as they are aligned so that each is in the desired pose. Also, note that convergence might be difficult to achieve when the two ligands are in different poses.
2. Flexible. In addition to tuning the force constants, you can turn on just the positional restraint, position + orientation, or all three position + orientation + rotation. See [this paper](https://pubs.acs.org/doi/10.1021/acs.jcim.1c01129), section "Test of the Alignment Restraints." You can also omit the alignment restraints. In this case, it is important to impose binding site restraints to keep the ligand in the solution from wandering away.

**Comment by egtai** [comment]
Hello, I have the following questions based on my free ability. I hope you can answer them when you are free. Thank you.

1. If the binding mode of two ligands at the same binding point increases, do I still need to perform a ligand arrangement operation? , because no matter which ligand arrangement is referenced, the binding mode of one ligand will always be changed. In this case, please tell me how to prepare my system and set up Basho to get accurate results in a timely manner.

**Comment by egtai** [comment]
Hello, I have the following questions about relative binding free energy. I hope you can answer them when you are free. Thank you.

1. If the binding modes of two ligands at the same binding site are quite different, do I still need to perform ligand alignment? , because no matter which ligand is referenced for alignment, the binding mode of one of the ligands will always be changed. In this case, how should I prepare my simulation system and what settings should I make so that I can get accurate results?

**Comment by egallicc** [comment]
ATM might not be the best tool to compare the binding free energies of ligands that do not share a similar pose.

That said, alignment restraints are technically optional. If there is no obvious way to align two ligands, omitting alignment restraints (for example by setting ALIGN_KF_SEP, ALIGN_K_THETA, ALIGN_K_PSI to zero) could be the best course of action.

**Comment by 9527567** [comment]
Understood, thank you.
