### ISSUE TITLE
ligand only transformations with changing charge

### ISSUE THREAD

**Issue by agoliaei** [Gallicchio-Lab/AToM-OpenMM#78]
Hi,
Thank you very much for sharing this work. This is really great!
This is a question, not an issue: is it possible to use this method for small molecule alchemical transfromations in explicit water where the charge is changed, such as the change in free energy upon protonation/deprotonation, no protein/receptor involved? How is the charge difference handled? I would appreciate it if you could point me to any script or tutorial available for a dual-topology scheme for this.
Thank you.

**Comment by egallicc** [comment]
Thanks. 

ATM is designed to model equilibria, such as non-covalent molecular binding, which are representable by a coordinate transformation. Protonation/deprotonation does not obviously fall into this category.

What is the context of the transformation you have in mind? Do you intend to calculate the difference of solvation free energies of the two species?

**Comment by agoliaei** [comment]
Thank you for replying. Yes. I am exploring various methods for calculating microscopic pKa estimates for small molecules and was wondering if this could be used. TI with explicit solvent is used in the literature, but most packages are slow.
https://link.springer.com/article/10.1007/s10822-018-0167-1

**Comment by egallicc** [comment]
Right. Computing pKa's from first principles is very hard because it involves changes in chemical bonds.

Computing pKa shifts--how the pKa of a species changes depending on the environment, such as receptor-bound vs. unbound--is much easier in comparison. It involves computing the free energy changes of transferring the acid and the conjugate base from one environment to the other. The latter could be done with ATM, in principle.

**Comment by agoliaei** [comment]
Thank you.
