### ISSUE TITLE
Doubts about replica exchange.

### ISSUE THREAD

**Issue by 9527567** [Gallicchio-Lab/AToM-OpenMM#80]
https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/b379d312c2568913466933c2fb3ed5e46b8710c1/async_re.py#L446
This function is responsible for determining and performing copy exchange.

---
 https://github.com/Gallicchio-Lab/AToM-OpenMM/blob/b379d312c2568913466933c2fb3ed5e46b8710c1/async_re.py#L283-L330
But here, is it expected behavior to determine whether the frequency of replica exchange is related to hardware options, such as the number of GPUs and the setting of jobqueues?
Further debugging revealed that when replicas 1 and 2 were completed, do_exchanges was called for replicas 1 and 2. After replicas 1, 2, 3, and 4 were completed, do_exchanges was called for replicas 1, 2, 3, and 4 and so on.
According to my understanding, the behavior of exchanging replicas after completing one sampling for all replicas is deterministic.

**Comment by egallicc** [comment]
I hope I am not misunderstanding your note, but as far as I know, replica exchanges are not required to be deterministic. Unless it is properly corrected, the only requirement is that the prior probability of selecting a lambda state for exchange is not biased toward a specific set of states. Because, asymptotically, all replicas host all lambda states with equal probability, this replica exchange algorithm is unbiased.

**Comment by 9527567** [comment]
Thank you, unfortunately I am not an expert in statistical mechanics. In synchronous code, `do_exchanges` is executed after sampling all replicas once. If I understand your meaning correctly, this is statistically consistent with asynchronous code, right?

**Comment by egallicc** [comment]
Sure. The standard Metropolis Monte Carlo sampling algorithm considers a symmetric alpha_mn = alpha_nm proposal probability matrix to convert state m into state n. For replica exchange, n and m are two of the many permutations of the assignments of alchemical states to replicas. If the proposal algorithm is symmetric (proposing to go from m to n has the same probability of proposing from n to m) then the algorithm samples the correct replica exchange distribution.

I am unfamiliar with the synchronous module (it is hosted here, but I was not involved in its development), but it seems to be making a straightforward all-to-all proposal, which is symmetric and, hence, valid. It is equivalent to the sampling in the asynchronous code, except that in asynchronous mode, exchanges are restricted to the subset of replicas that are not currently running.

Have you noticed any misbehavior that could be due to biased replica exchange sampling?

**Comment by 9527567** [comment]
Thank you, I am just confused about this part, there is no inappropriate behavior here. Now I understand.
