### ISSUE TITLE
explicit setting for RBFE simulation length instead of wallclock

### ISSUE THREAD

**Issue by blakemertz** [Gallicchio-Lab/AToM-OpenMM#82]
Thanks for providing slurm scripts to execute these examples -- really makes the bar for learning the AToM approach so much lower :-)

Looking through the posts to github and the [user manual](https://www.compmolbiophysbc.org/atom-openmm/atom-control-file) on the labs website, I wanted to know if there is a way to specify a simulation length for an RBFE run? (Have not found a clear indication based on my reading of those two sources beyond this particular issue #6 . The RBFE example for eralpha is to set a wallclock time of 2 hours. Executing a run for a wallclock time can produce widely different results depending on the GPU hardware that is being used.

If I wanted to reproduce the 10 ns per replica given in Azimi et al. JCIM 2022 for eralpha, do I simply set PRODUCTION_STEPS in the .cntl file to 5,000,000 and turn off WALL_TIME? Or do I need to set MAX_SAMPLES once I get a better idea of how much simulation time I need to get convergence?

**Comment by egallicc** [comment]
Thank you for the feedback.

Right, it is easy to get confused. The names of these keywords are less than optimal. Unfortunately, they have been set long ago, and it is difficult to change them without breaking old input files.

In short, to run 10 ns per replica, a possible setup is:
```
PRODUCTION_STEPS = 20000
MAX_SAMPLES = 250
TIME_STEP = 0.002
```
(2 fs x 20000 steps x 250 samples)

Set `WALL_TIME` to the wall-clock time in minutes you want the job to run for before terminating gracefully. We typically set `WALL_TIME = 1200` for Slurm jobs with a 24h time limit. Relaunch the job multiple times until the specified number of samples is collected. 

Note that `PRODUCTION_STEPS` is not the length of the simulation. It is the number of MD steps a replica runs on the GPU before being replaced by another replica. See https://www.compmolbiophysbc.org/atom-openmm/atom-control-file#h.jg9bis8vwpjn

**Comment by shuzhewang-iso** [comment]
thanks @egallicc , is MAX_SAMPLES = 250 a good empirical val for most small molecules? I suppose fragment-sized molecules can have a quite bit smaller MAX_SAMPLE?

**Comment by egallicc** [comment]
The appropriate simulation length to reach convergence depends on many factors. For protein-ligand systems, a few nanoseconds per replica is probably the absolute minimum to converge simple RBFE calculations. To the other extreme, we have examples of ABFE calculations for fragment-sized molecules that did not reach convergence after more than 50 ns/replica due to receptor reorganization.

Also, note that the meaning of a "sample" depends on the MD time step (`TIME_STEP`) and the number of MD steps between samples (`PRODUCTION_STEPS`).  ns/replica is a more portable measure of simulation length.
